name: github action infra creation

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}  # âœ” fixed spelling
  STATE_FILE: ${{ secrets.STATE_FILE }}

jobs:
  Build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Install
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "latest"
      
      - name: Terraform init azurerm backend
        uses: ahmedig/terraform-azurerm-backend@v4
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          resource_group_name: ${{ secrets.RESOURCE_GROUP }}
          container_name: ${{ secrets.CONTAINER_NAME }}
          storage_account_name: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          tf_working_directory: ./resource_group

      - name: Terraform Validate
        uses: tf-actions/validate@v1
        with:
          tf_working_directory: ./resource_group

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./resource_group

      - name: Terraform Apply
        run: terraform apply --auto-approve
        working-directory: ./resource_group
